services:
  drip:
    image: haumea/drip:latest
    container_name: drip
    ports:
      - 5001:5001
    volumes:
      - drip-data:/data
    environment:
      DRIP_BASE_URL: http://localhost:5001

volumes:
  drip-data:
